---
- name: Ajout d'un répertoire de travail
  become: yes
  when: item.repo is undefined 
  file: path=/home/{{ user }}/{{ item.domain }} state=directory owner={{ user }}

- name: Clonage d'un git
  become: yes
  when: item.repo is defined
  git: repo={{ item.repo }} dest=/home/{{ user }}/{{ item.domain }} clone=yes

- name: Création du lien symbolique
  become: yes
  file: src=/home/{{ user }}/{{ item.domain }} dest=/var/www/html/{{ item.domain }} state=link
- name: Envoi du fichier de conf
  become: yes
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ item.domain }}
- name: Création du lien symbolique
  become: yes
  file: src=/etc/nginx/sites-available/{{ item.domain }} dest=/etc/nginx/sites-enabled/{{ item.domain }} state=link
  notify: nginx reloaded
...
