---
- name: "Play Docker Images"
  hosts: docker
  remote_user: root
  gather_facts: no
  vars_files:
   - secret.yml

  tasks:
#   - name: "Pull docker image"
#     shell: "docker pull tutum/apache-php"
#   - name: "Start docker image"
#     shell: "docker run -d -p 80:80 tutum/apache-php"
   - name: "Login to docker hub"
     docker_login:
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"
   - name: "Create custom Docker container"
     docker_container:
      name: mycustomcontainer
      image: antanof/httpd_v1:1
      state: started
      exposed_ports: "80"
      ports: "80:80"
...
