---
- name: "install SQUID Proxy"
  hosts: webservers
  remote_user: root
  gather_facts: no
  vars:
   state: present

  tasks:
   - name: "Install SQUID package"
     apt: name=squid3 state={{ state }}
   - name: "Sauvegarde du fichier de conf SQUID"
     shell: "cp /etc/squid3/squid.conf /etc/squid3/squid.bak"
   - name: "Paramètres de conf de SQUID 1/2"
     lineinfile: dest=/etc/squid3/squid.conf line='acl localnet 10.0.0.0/8' insertafter='^#?acl[\s]localnet'
   - name: "Paramètres de conf de SQUID 2/2"
     lineinfile: dest=/etc/squid3/squid.conf line='http_access allow localnet' insertafter='^#http_access allow localnet'
   - name: "Redémarrage de SQUID"
     service: name=squid3 state=restarted
...
