- hosts: ubuntu
  become: yes
  tasks:
   - name: Make sure we can connect
     ping:
   - name: Install required tools
     apt: name={{item}} state=installed
     with_items:
      - unzip
# PHP
   - name: Add the ondel PHP PPA
     apt_repository: repo='ppa:ondrej/php'
   - name: Update the apt cache
     apt: update_cache=yes cache_valid_time=3600
   - name: Install PHP
     apt: name={{ item }} state=installed
     with_items:
      - php
      - php-fpm
      - php-mysql
      - php-xml
   - name: Remove Apache2
     apt: name=apache2 state=removed
# MySQL
   - name: Install MySQL
     apt: name={{ item }} state=installed
     with_items:
      - mysql-server
      - python-mysqldb
   - name: Generate new root password
     command: openssl rand -hex 7 creates=/root/.my.cnf
     register: mysql_new_root_pass
   - name: Remove anonymous users
     mysql_user: name="" state=absent
     when: mysql_new_root_pass.changed
   - name: Remove test database
     mysql_db: name=test state=absent
     when: mysql_new_root_pass.changed
   - name: Output new root password
     debug: 
      msg: "New root password is {{mysql_new_root_pass.stdout}}"
     when: mysql_new_root_pass.changed   
   - name: Update root password
     mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
     with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
     when: mysql_new_root_pass.changed
   - name: Create my.cnf
     template: src=templates/mysql/mycnf.j2 dest=/root/.my.cnf
     when: mysql_new_root_pass.changed
# Nginx
   - name: Install Nginx
     apt: name=nginx state=installed
   - name: Start Nginx
     service: name=nginx state=started
   - name: Create Nginx config
     template: src=templates/nginx/default.j2 dest=/etc/nginx/sites-available/default 
     notify: restart Nginx
# Wordpress
   - name: Get Wordpress checksum
     uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
     register: wp_checksum
   - name: Download Wordpress
     get_url: url=https://wordpress.org/latest.zip dest=/tmp/wordpress.zip checksum="sha1:{{wp_checksum.content}}" 
#   - name: Install required tools
#     apt: name=unzip state=installed
   - name: Unzip Wordpress
     unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no creates=/tmp/wordpress/wp-settings.php
   - name: Create project folder
     file: dest=/var/www/site1.org state=directory
   - name: Copy Wordpress files
     command: cp -a /tmp/wordpress/. /var/www/site1.org creates=/var/www/site1.org/wp-settings.php
   - name: Create Wordpress database
     mysql_db: name=wordpress state=present
   - name: Create Wordpress database user
     mysql_user: name=wordpress host=localhost password=P4ssw0rd priv=wordpress.*:ALL
   - name: Create wp-config
     template: src=templates/wordpress/wp-config.j2 dest=/var/www/site1.org/wp-config.php
   - name: Does the database exist ?
     command: mysql -u root wordpress -e "SELECT ID FROM wordpress.wp_users LIMIT 1;"
     register: db_exist
     ignore_errors: true
     changed_when: false
   - name: Copy Wordpress database
     copy: src=files/wp-database.sql dest=/tmp/wp-database.sql
     when: db_exist.rc > 0
   - name: Import Wordpress database
     mysql_db: target=/tmp/wp-database.sql state=import name=wordpress
     when: db_exist.rc > 0
...
